reviews:
  # 直接在主配置文件中引用路徑指令
  path_instructions:
    - path: "**/*.{cpp,h}"
      instructions: |
        請針對此 C++ 程式碼進行以下漏洞檢查：
        1. 檢查是否存在緩衝區溢位問題（例如使用 strcpy、sprintf 等函數，並寫入超過緩衝區大小）。
        2. 檢查是否有無終止條件的遞迴呼叫導致堆疊溢位。
        3. 檢查是否存在使用未初始化記憶體的情況。
        4. 檢查是否有空指標解引用的問題。
        5. 檢查是否存在野指標問題（例如使用後釋放的記憶體）。
        6. 檢查是否有記憶體洩漏（未釋放的分配記憶體）。
        7. 檢查是否存在雙重釋放記憶體的風險。
        8. 檢查是否存在未驗證輸入導致緩衝區溢位的狀況。
        9. 檢查是否有條件競爭的多執行緒操作（共享變數操作無同步機制）。
        10. 檢查是否存在邏輯錯誤（例如錯誤的 if 條件）。
        11. 檢查是否有無限迴圈或死循環狀況。
        12. 檢查是否有未處理的錯誤（例如未檢查文件打開返回值）。
        13. 檢查是否有硬編碼的認證資訊（用戶名稱、密碼）。
        14. 檢查是否存在未授權存取敏感檔案（例如 /etc/shadow）的問題。
        15. 檢查是否有資訊洩漏問題（直接打印敏感資訊）。
        16. 檢查是否有資源飢餓問題，例如不斷忙碌的無限迴圈。
        17. 檢查是否有通訊協定解析錯誤風險。
